#!/bin/bash
# PreToolUse Hook: Block dangerous operations
#
# Triggered before: All tool executions
# Exit codes:
#   0 = Allow (continue with tool)
#   2 = Block (prevent tool execution)
#
# Environment variables available:
#   CLAUDE_TOOL_NAME - Name of the tool being called
#   CLAUDE_TOOL_ARG_FILE_PATH - File path argument
#   CLAUDE_TOOL_ARG_COMMAND - Command argument (for Bash)

set -e

FILE_PATH="${CLAUDE_TOOL_ARG_FILE_PATH:-}"
COMMAND="${CLAUDE_TOOL_ARG_COMMAND:-}"

# === EDIT/WRITE PROTECTIONS ===
if [[ "$CLAUDE_TOOL_NAME" == "Edit" || "$CLAUDE_TOOL_NAME" == "Write" ]]; then

  # Block convex/_generated modifications
  if [[ "$FILE_PATH" == *"convex/_generated"* ]]; then
    echo "BLOCKED: Cannot modify Convex generated files"
    echo "These files are auto-generated by 'npx convex dev'"
    exit 2
  fi

  # Block node_modules
  if [[ "$FILE_PATH" == *"node_modules"* ]]; then
    echo "BLOCKED: Cannot modify node_modules"
    echo "Use npm to manage dependencies instead"
    exit 2
  fi

  # Block .env files (except .env.example)
  if [[ "$FILE_PATH" == *".env"* && "$FILE_PATH" != *".env.example"* && "$FILE_PATH" != *".env.local.example"* ]]; then
    echo "BLOCKED: Cannot modify .env files"
    echo "Environment files may contain secrets"
    exit 2
  fi

  # Block package-lock.json direct edits
  if [[ "$FILE_PATH" == *"package-lock.json" ]]; then
    echo "BLOCKED: Cannot modify package-lock.json directly"
    echo "Use npm install to update dependencies"
    exit 2
  fi

fi

# === BASH COMMAND PROTECTIONS ===
if [[ "$CLAUDE_TOOL_NAME" == "Bash" ]]; then

  # Block force push to main/master
  if [[ "$COMMAND" == *"git push"*"--force"* ]]; then
    if [[ "$COMMAND" == *"main"* || "$COMMAND" == *"master"* ]]; then
      echo "BLOCKED: Force push to main/master is not allowed"
      echo "This could destroy commit history"
      exit 2
    fi
  fi

  # Block hard reset
  if [[ "$COMMAND" == *"git reset --hard"* ]]; then
    echo "BLOCKED: Hard reset requires explicit user approval"
    echo "This could lose uncommitted work"
    exit 2
  fi

  # Block rm -rf on sensitive directories
  if [[ "$COMMAND" == *"rm -rf"* ]]; then
    if [[ "$COMMAND" == *"/"* && ! "$COMMAND" == *"node_modules"* && ! "$COMMAND" == *".next"* && ! "$COMMAND" == *"dist"* ]]; then
      echo "BLOCKED: Dangerous rm -rf command"
      echo "Only allowed for: node_modules, .next, dist"
      exit 2
    fi
  fi

  # Block database drops
  if [[ "$COMMAND" == *"convex"*"--clear"* ]]; then
    echo "BLOCKED: Database clear requires explicit user approval"
    exit 2
  fi

fi

# All checks passed
exit 0
