#!/usr/bin/env npx tsx

/**
 * generate-report.ts — Post-ingest report pipeline.
 *
 * Flow: query Convex → GPT synthesis → HTML template → store in Convex → send Telegram summary
 *
 * Usage:
 *   npx tsx scripts/generate-report.ts --station-code FR-PSUA-DIF1 --year 2026 --week 14
 *   npx tsx scripts/generate-report.ts --station-code FR-PSUA-DIF1  # auto-detect latest week
 *
 * Env vars required:
 *   CONVEX_URL / NEXT_PUBLIC_CONVEX_URL
 *   CONVEX_DEPLOY_KEY
 *   OPENAI_API_KEY
 *   TELEGRAM_BOT_TOKEN (optional — for sending summary)
 *   TELEGRAM_CHAT_ID (optional — target chat)
 */

import { ConvexHttpClient } from "convex/browser";

import { api } from "../convex/_generated/api";
import type { DriverRecommendation, ReportData, WeeklyHistoryEntry } from "../src/lib/pdf/report-template";
import { generateReportHtml } from "../src/lib/pdf/report-template";
import * as fs from "node:fs";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyDriver = any;

// ---------------------------------------------------------------------------
// Args
// ---------------------------------------------------------------------------

function parseArgs() {
  const args = process.argv.slice(2);
  const get = (flag: string) => {
    const idx = args.indexOf(flag);
    return idx >= 0 && idx + 1 < args.length ? args[idx + 1] : undefined;
  };

  const stationCode = get("--station-code") ?? "FR-PSUA-DIF1";
  const year = get("--year") ? Number(get("--year")) : undefined;
  const week = get("--week") ? Number(get("--week")) : undefined;
  const outputDir = get("--output-dir") ?? ".artifacts/reports";
  const aiFile = get("--ai-file"); // JSON file with aiSummary, aiRecommendations, driverRecommendations
  const skipTelegram = args.includes("--skip-telegram");
  const blurNames = args.includes("--blur-names");

  return { stationCode, year, week, outputDir, aiFile, skipTelegram, blurNames };
}

// ---------------------------------------------------------------------------
// AI content (loaded from file — generated by OpenClaw/GPT 5.4)
// ---------------------------------------------------------------------------

interface AiContent {
  aiSummary: string;
  aiRecommendations: string;
  driverRecommendations: DriverRecommendation[];
}

function loadAiContent(filePath: string): AiContent {
  const raw = fs.readFileSync(filePath, "utf-8");
  return JSON.parse(raw) as AiContent;
}

// ---------------------------------------------------------------------------
// Telegram
// ---------------------------------------------------------------------------

async function sendTelegramSummary(text: string) {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID ?? process.env.DSPILOT_MAIN_GROUP_ID;
  if (!token || !chatId) {
    console.log("[telegram] skipped — no TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID");
    return;
  }

  const url = `https://api.telegram.org/bot${token}/sendMessage`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: chatId,
      text,
      parse_mode: "HTML",
      disable_web_page_preview: true,
    }),
  });

  if (!res.ok) {
    console.error("[telegram] send failed:", await res.text());
  } else {
    console.log("[telegram] summary sent");
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const opts = parseArgs();
  const convexUrl = process.env.CONVEX_URL ?? process.env.NEXT_PUBLIC_CONVEX_URL;
  if (!convexUrl) {
    console.error("CONVEX_URL or NEXT_PUBLIC_CONVEX_URL required");
    process.exit(1);
  }

  const client = new ConvexHttpClient(convexUrl);
  // Admin auth for deploy-key access (bypasses Clerk)
  const deployKey = process.env.CONVEX_DEPLOY_KEY;
  if (deployKey) {
    (client as unknown as { setAdminAuth(t: string): void }).setAdminAuth(deployKey);
  }

  // Auto-detect year/week if not provided
  let { year, week } = opts;
  if (!year || !week) {
    console.log("[report] auto-detecting latest week with data...");
    // Use the getLatestWeekWithData or just query stationWeeklyStats
    const now = new Date();
    const isoWeek = getISOWeek(now);
    year = year ?? now.getFullYear();
    week = week ?? isoWeek;
    console.log(`[report] using week ${week}/${year}`);
  }

  // Step 1: Query Convex for report data
  console.log(`[report] querying data for ${opts.stationCode} S${week}/${year}...`);
  const reportData = await client.query(api.reporting.getReportData, {
    stationCode: opts.stationCode,
    year,
    week,
  });

  if (!reportData) {
    console.error(`[report] no data found for ${opts.stationCode} S${week}/${year}`);
    process.exit(1);
  }

  console.log(`[report] ${reportData.drivers.length} drivers, DWC avg ${reportData.kpis.avgDwc}%`);

  // Step 2: Load AI content (generated by OpenClaw)
  let aiContent: AiContent = {
    aiSummary: "",
    aiRecommendations: "",
    driverRecommendations: [],
  };

  if (opts.aiFile) {
    console.log(`[report] loading AI content from ${opts.aiFile}...`);
    try {
      aiContent = loadAiContent(opts.aiFile);
      console.log(`[report] AI content loaded — ${aiContent.driverRecommendations.length} driver recommendations`);
    } catch (err) {
      console.error("[report] failed to load AI content, continuing without:", err);
    }
  } else {
    console.log("[report] no --ai-file provided, generating without AI synthesis");
  }

  // Step 3: Build ReportData and generate HTML
  const top5 = reportData.drivers.slice(0, 5) as AnyDriver[];
  const bottom5 = (reportData.drivers as AnyDriver[]).filter((d: AnyDriver) => d.dwcPercent < 90).slice(-5);

  // Map weeklyHistory from Convex format
  const weeklyHistory: WeeklyHistoryEntry[] | undefined = reportData.weeklyHistory
    ? (reportData.weeklyHistory as { week: number; year: number; avgDwc: number; avgIadc: number }[]).map((h) => ({
        week: h.week,
        year: h.year,
        avgDwc: h.avgDwc,
        avgIadc: h.avgIadc,
      }))
    : undefined;

  const templateData: ReportData = {
    stationName: reportData.stationName,
    stationCode: reportData.stationCode,
    week,
    year,
    generatedAt: new Date().toLocaleString("fr-FR", { timeZone: "Europe/Paris" }),
    kpis: reportData.kpis,
    dwcDistribution: reportData.dwcDistribution,
    topDrivers: top5.map((d: AnyDriver) => ({
      rank: d.rank,
      name: d.name,
      dwcPercent: d.dwcPercent,
      iadcPercent: d.iadcPercent,
      daysWorked: d.daysWorked,
      trend: d.dwcTrend ?? undefined,
    })),
    bottomDrivers: bottom5.map((d: AnyDriver) => ({
      rank: d.rank,
      name: d.name,
      dwcPercent: d.dwcPercent,
      iadcPercent: d.iadcPercent,
      daysWorked: d.daysWorked,
      trend: d.dwcTrend ?? undefined,
    })),
    allDrivers: (reportData.drivers as AnyDriver[]).map((d: AnyDriver) => ({
      rank: d.rank,
      name: d.name,
      dwcPercent: d.dwcPercent,
      iadcPercent: d.iadcPercent,
      daysWorked: d.daysWorked,
      trend: d.dwcTrend ?? undefined,
    })),
    aiSummary: aiContent.aiSummary || undefined,
    aiRecommendations: aiContent.aiRecommendations || undefined,
    driverRecommendations: aiContent.driverRecommendations.length > 0 ? aiContent.driverRecommendations : undefined,
    weeklyHistory,
    dnr: reportData.dnr ?? undefined,
  };

  // Generate both versions
  const htmlDsp = generateReportHtml(templateData, { blurNames: false });
  const htmlLivreurs = generateReportHtml(templateData, { blurNames: true });

  // Step 4: Save to disk
  fs.mkdirSync(opts.outputDir, { recursive: true });
  const baseName = `rapport-s${week}-${year}-${reportData.stationCode.toLowerCase()}`;
  const dspPath = `${opts.outputDir}/${baseName}-dsp.html`;
  const livreursPath = `${opts.outputDir}/${baseName}-livreurs.html`;
  fs.writeFileSync(dspPath, htmlDsp);
  fs.writeFileSync(livreursPath, htmlLivreurs);
  console.log(`[report] saved: ${dspPath} (${(htmlDsp.length / 1024).toFixed(1)} KB)`);
  console.log(`[report] saved: ${livreursPath} (${(htmlLivreurs.length / 1024).toFixed(1)} KB)`);

  // Step 5: Store in Convex
  console.log("[report] storing in Convex...");
  try {
    await client.mutation(api.reporting.storeReport, {
      stationId: reportData.stationId,
      reportType: "weekly",
      logicalChannel: "reports_weekly",
      audience: "manager",
      periodLabel: `S${week} ${year}`,
      year,
      week,
      title: `Rapport Hebdomadaire S${week} — ${reportData.stationCode}`,
      summary: aiContent.aiSummary
        ? aiContent.aiSummary.replace(/<[^>]*>/g, "").slice(0, 500)
        : `DWC ${reportData.kpis.avgDwc}%, ${reportData.kpis.activeDrivers} livreurs actifs`,
      asciiContent: `DWC: ${reportData.kpis.avgDwc}% | IADC: ${reportData.kpis.avgIadc}% | Drivers: ${reportData.kpis.activeDrivers}`,
      htmlContent: htmlDsp,
      pdfStatus: "pending",
      deliveryStatus: "pending",
      confidenceScore: 0.9,
    });
    console.log("[report] stored in Convex ✓");
  } catch (err) {
    console.error("[report] Convex store failed:", err);
  }

  // Step 6: Telegram summary
  if (!opts.skipTelegram) {
    const tgText = [
      `<b>📊 Rapport S${week} — ${reportData.stationCode}</b>`,
      "",
      `DWC: <b>${reportData.kpis.avgDwc}%</b>${reportData.kpis.dwcChange !== undefined ? ` (${reportData.kpis.dwcChange >= 0 ? "+" : ""}${reportData.kpis.dwcChange}pp)` : ""}`,
      `IADC: <b>${reportData.kpis.avgIadc}%</b>`,
      `Livreurs: ${reportData.kpis.activeDrivers}/${reportData.kpis.totalDrivers}`,
      "",
      `≥95%: ${reportData.dwcDistribution.above95} | 90-95%: ${reportData.dwcDistribution.pct90to95} | <90%: ${reportData.dwcDistribution.pct85to90 + reportData.dwcDistribution.pct80to85 + reportData.dwcDistribution.below80}`,
      "",
      aiContent.aiSummary ? aiContent.aiSummary.replace(/<[^>]*>/g, "") : "",
      "",
      `Rapport HTML généré — ${(htmlDsp.length / 1024).toFixed(0)} KB`,
    ].join("\n");

    await sendTelegramSummary(tgText);
  }

  console.log("[report] done ✓");
}

function getISOWeek(date: Date): number {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  return Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
}

main().catch((err) => {
  console.error("[report] fatal:", err);
  process.exit(1);
});
